[package]
name = "poll-reactive"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A minimalistic poll-based reactive library"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
