# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# https://github.com/rust-lang/rustup/issues/3409
# https://github.com/dtolnay/rust-toolchain

name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # at 00:00 every Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - "1.77.0"
          - stable
          - nightly

    name: Rust ${{ matrix.rust }}

    steps:
      - uses: actions/checkout@master

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo build
        run:
          cargo build

      - name: Run cargo test
        run:
          cargo test

      - name: Run cargo publish (dry-run)
        run:
          cargo publish --dry-run