on:
  push:
    tags:
      - '*'

name: publish

jobs:

  check_and_publish:
    name: Check & Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test
        run:
          cargo test

      - name: Run cargo login
        run:
          cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: Run cargo publish
        run:
          cargo publish