# References:
# - https://users.rust-lang.org/t/does-anyone-use-github-actions-to-run-cargo-publish/92374
# - https://github.com/azriel91/fn_graph/blob/main/.github/workflows/publish.yml
# - https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1
#
# To push a new version, use `./scripts/add_tag_and_publish.sh`
#

on:
  push:
    tags:
      - '*'

name: publish

jobs:

  check_and_publish:
    name: Check & Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test
        run:
          cargo test

      - name: Run cargo login
        run:
          cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: Run cargo publish
        run:
          cargo publish